// AUTO-GENERATED by scripts/build-tdx-pois.ts
// Source: TDX 觀光署 API + Claude Haiku 4.5 enrichment
// Generated: 2026-05-31T03:22:22.632Z
// Count: 5446 POIs across 13 cities
// 不要手改, 重跑 pnpm tdx:build 會被蓋掉
//
// 為什麼用 JSON import + cast: TS 對 5446 個 literal type 推導會 "union too complex" → 改 import JSON
import dataJson from "./tdx-pois.json";
import type { Poi } from "./mock-data";

export const tdxPois = dataJson as unknown as Poi[];
