/**
 * Step 3: 把 enriched JSON 轉成 TypeScript module 給 mock-data.ts 用
 *
 * 用法: pnpm tdx:build
 *
 * 讀: data/pois-enriched.json
 * 寫: lib/tdx-pois.ts (合進 mock-data.ts 的 pois 陣列)
 *
 * 過濾規則:
 *   - kidScore >= 5
 *   - 有有效座標 (lat/lng != 0)
 *   - 有地址
 */
import * as fs from "node:fs";
import * as path from "node:path";
import type { EnrichedPoi } from "./types";

const INPUT_PATH = path.join(process.cwd(), "data", "pois-enriched.json");
const OUTPUT_PATH = path.join(process.cwd(), "lib", "tdx-pois.ts");

function fail(msg: string): never {
  console.error(`❌ ${msg}`);
  process.exit(1);
}

function safe(s: string | undefined): string {
  if (!s) return "";
  return s.replace(/"/g, '\\"').replace(/\n/g, " ").trim();
}

function main() {
  if (!fs.existsSync(INPUT_PATH)) {
    fail(`找不到 ${INPUT_PATH}. 先跑 pnpm tdx:enrich`);
  }
  const enriched: EnrichedPoi[] = JSON.parse(fs.readFileSync(INPUT_PATH, "utf-8"));
  console.log(`📂 載入 ${enriched.length.toLocaleString()} 筆 enriched POI`);

  // 過濾: 只要 name + kidScore 夠 + 有 city/address 其一 (district/lat/lng 可缺)
  const filtered = enriched.filter((p) => {
    if (p.kidScore < 5) return false;
    if (!p.name) return false;
    if (!p.city && !p.address) return false;
    return true;
  });

  console.log(`✓ 通過過濾: ${filtered.length.toLocaleString()} (刪掉 ${(enriched.length - filtered.length).toLocaleString()} 筆無效)`);

  // 統計
  const byCategory = filtered.reduce<Record<string, number>>((acc, p) => {
    acc[p.category] = (acc[p.category] ?? 0) + 1;
    return acc;
  }, {});
  const byCity = filtered.reduce<Record<string, number>>((acc, p) => {
    acc[p.city] = (acc[p.city] ?? 0) + 1;
    return acc;
  }, {});

  // 寫 TS 模組
  const header = `// AUTO-GENERATED by scripts/build-tdx-pois.ts
// Source: TDX 觀光署 API + Claude Haiku 4.5 enrichment
// Generated: ${new Date().toISOString()}
// Count: ${filtered.length} POIs across ${Object.keys(byCity).length} cities
// 不要手改, 重跑 pnpm tdx:build 會被蓋掉
import type { Poi } from "./mock-data";

export const tdxPois: Poi[] = [
`;

  const body = filtered
    .map((p) => {
      const isFree = p.priceMin === 0 && p.priceMax === 0;
      // 字數限制 description
      const desc = safe(p.description).slice(0, 200) || `位於${p.district}, 親子推薦.`;
      const photosLine = p.photos.length > 0
        ? `\n    photos: ${JSON.stringify(p.photos)},`
        : "";
      const district = p.district || p.city || "未分類";
      const address = p.address || `${p.city ?? ""}${p.district ?? ""}`.trim() || null;
      return `  {
    id: ${JSON.stringify(p.id)},
    name: ${JSON.stringify(p.name)},
    category: ${JSON.stringify(p.category)},
    district: ${JSON.stringify(district)},
    ageMin: ${p.ageMin},
    ageMax: ${p.ageMax},
    durationMin: ${p.durationMin},
    priceMin: ${p.priceMin},
    priceMax: ${p.priceMax},
    description: ${JSON.stringify(desc)},
    tags: ${JSON.stringify(p.parentingTags)},
    likes: ${Math.round(p.kidScore * 100 + Math.random() * 200)},
    contributorName: "TDX",
    estimatedKid: ${JSON.stringify(p.aiReasoning)},${p.phone ? `\n    phone: ${JSON.stringify(p.phone)},` : ""}
    requiresReservation: ${p.category === "restaurant" && !isFree},
    address: ${address ? JSON.stringify(address) : "undefined"},${photosLine}
  },`;
    })
    .join("\n");

  const footer = `\n];\n`;

  fs.writeFileSync(OUTPUT_PATH, header + body + footer);

  const fileSize = fs.statSync(OUTPUT_PATH).size;
  console.log(`\n✅ 完成: ${OUTPUT_PATH} (${(fileSize / 1024).toFixed(0)} KB)`);
  console.log(`\n📊 統計:`);
  console.log(`   類別分佈:`);
  for (const [cat, n] of Object.entries(byCategory).sort((a, b) => b[1] - a[1])) {
    console.log(`     ${cat.padEnd(10)} ${String(n).padStart(5)}`);
  }
  console.log(`   縣市分佈 (前 10):`);
  for (const [city, n] of Object.entries(byCity).sort((a, b) => b[1] - a[1]).slice(0, 10)) {
    console.log(`     ${city.padEnd(6)} ${String(n).padStart(5)}`);
  }

  console.log(`\n下一步: 在 lib/mock-data.ts 加 import + merge`);
  console.log(`  import { tdxPois } from "./tdx-pois";`);
  console.log(`  export const pois: Poi[] = [...handCurated, ...seedPois, ...tdxPois];`);
}

main();
